apiVersion: cluster.x-k8s.io/v1beta2
kind: Cluster
metadata:
  labels:
    ccm: external
    cluster.x-k8s.io/cluster-name: ${CLUSTER_NAME}
  name: ${CLUSTER_NAME}
  namespace: ${NAMESPACE}
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - ${POD_CIDR:="192.168.0.0/16"}
    serviceDomain: ${SERVICE_DOMAIN:="cluster.local"}
    services:
      cidrBlocks:
      - ${SERVICE_CIDR:="10.128.0.0/12"}
  topology:
    classRef:
      name: ${IBMVPC_CLUSTER_CLASS_NAME}
    controlPlane:
      replicas: ${CONTROL_PLANE_MACHINE_COUNT}
    version: ${KUBERNETES_VERSION}
    workers:
      machineDeployments:
        - class: default-worker
          name: md-0
          replicas: ${WORKER_MACHINE_COUNT}
---
apiVersion: cluster.x-k8s.io/v1beta2
kind: ClusterClass
metadata:
  name: ${IBMVPC_CLUSTER_CLASS_NAME:="vpc-cc"}
spec:
  controlPlane:
    machineInfrastructure:
      ref:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
        kind: IBMVPCMachineTemplate
        name: ${IBMVPC_CLUSTER_CLASS_NAME}-control-plane-machinetemplate
    ref:
      apiVersion: controlplane.cluster.x-k8s.io/v1beta2
      kind: KubeadmControlPlaneTemplate
      name: ${IBMVPC_CLUSTER_CLASS_NAME}-control-plane
  infrastructure:
    ref:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
      kind: IBMVPCClusterTemplate
      name: ${IBMVPC_CLUSTER_CLASS_NAME}-cluster-template
  workers:
    machineDeployments:
      - class: default-worker
        template:
          bootstrap:
            ref:
              apiVersion: bootstrap.cluster.x-k8s.io/v1beta2
              kind: KubeadmConfigTemplate
              name: ${IBMVPC_CLUSTER_CLASS_NAME}-md-0
          infrastructure:
            ref:
              apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
              kind: IBMVPCMachineTemplate
              name: ${IBMVPC_CLUSTER_CLASS_NAME}-worker-machinetemplate
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: IBMVPCClusterTemplate
metadata:
  name: ${IBMVPC_CLUSTER_CLASS_NAME}-cluster-template
spec:
  template:
    spec:
      controlPlaneLoadBalancer:
        name: ${CLUSTER_NAME}-load-balancer
      region: ${IBMVPC_REGION}
      resourceGroup: ${IBMVPC_RESOURCEGROUP}
      vpc: ${IBMVPC_NAME}
      zone: ${IBMVPC_ZONE}
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta2
kind: KubeadmControlPlaneTemplate
metadata:
  name: ${IBMVPC_CLUSTER_CLASS_NAME}-control-plane
  namespace: ${NAMESPACE}
spec:
  template:
    spec:
      kubeadmConfigSpec:
        clusterConfiguration:
          apiServer:
            certSANs: [localhost, 127.0.0.1]
          controllerManager:
            extraArgs:
              - name: enable-hostpath-provisioner
                value: 'true'
              - name: cloud-provider
                value: external
          dns: {}
          etcd: {}
          scheduler: {}
        initConfiguration:
          nodeRegistration:
            criSocket: /var/run/containerd/containerd.sock
            kubeletExtraArgs:
              - name: cloud-provider
                value: external
              - name: eviction-hard
                value: 'nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%'
        joinConfiguration:
          discovery: {}
          nodeRegistration:
            criSocket: /var/run/containerd/containerd.sock
            kubeletExtraArgs:
              - name: cloud-provider
                value: external
              - name: eviction-hard
                value: 'nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%'
